KRISTINA VEZBA/Models/Order.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace KRISTINA_VEZBA.Models
{
    public class Order
    {
        
        public int OrderId { get; set; }

        public List<OrderDetail>? OrderDetails { get; set; }

        [Required(ErrorMessage = "Please enter your first name")]
        [Display(Name = "First name")]
        [StringLength(50)]
        public string FirstName { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter your last name")]
        [Display(Name = "Last name")]
        [StringLength(50)]
        public string LastName { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter your address")]
        [StringLength(100)]
        [Display(Name = "Address Line 1")]
        public string AddressLine1 { get; set; } = string.Empty;

        [Display(Name = "Address Line 2")]
        public string? AddressLine2 { get; set; }

        [Required(ErrorMessage = "Please enter your zip code")]
        [Display(Name = "Zip code")]
        [StringLength(10, MinimumLength = 4)]
        public string ZipCode { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter your city")]
        [StringLength(50)]
        public string City { get; set; } = string.Empty;

        [StringLength(10)]
        public string? State { get; set; }

        [Required(ErrorMessage = "Please enter your country")]
        [StringLength(50)]
        public string Country { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter your phone number")]
        [StringLength(25)]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone number")]
        public string PhoneNumber { get; set; } = string.Empty;

        [Required]
        [StringLength(50)]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|""(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*"")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])",
            ErrorMessage = "The email address is not entered in a correct format")]
        public string Email { get; set; } = string.Empty;

        [BindNever]
        public decimal OrderTotal { get; set; }

        [BindNever]
        public DateTime OrderPlaced { get; set; }

       
    }
}

KRISTINA VEZBA/Controllers/OrderController.cs
using KRISTINA_VEZBA.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace KRISTINA_VEZBA.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly IShoppingCart _shoppingCart;
        
        public OrderController(IOrderRepository orderRepository, IShoppingCart shoppingCart)
        {
            _orderRepository = orderRepository;
            _shoppingCart = shoppingCart;
        }

        public IActionResult Checkout()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            if (_shoppingCart.ShoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your cart is empty, add some pies first.");
            }
            if (ModelState.IsValid)
            {
                _orderRepository.CreateOrder(order);
                _shoppingCart.ClearCart();
                return RedirectToAction("CheckoutComplete");
            }
            return View(order);
        }
        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = "Thanks for your order. You'll soon enjoy our delicious pies!";
            return View();
        }

        public IActionResult Details(int orderId)
        {
            var order = _orderRepository.GetOrderById(orderId);
            if (order == null)
                return NotFound();
            return View(order);
        }

        public IActionResult OrderHistory(string Username)
        {
            var orders = _orderRepository.GetAllOrders(Username);
            return View(orders);
        }
    }

}

KRISTINA VEZBA/Controllers/PieController.cs
using KRISTINA_VEZBA.Models;
using KRISTINA_VEZBA.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace KRISTINA_VEZBA.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ICategoryRepository _categoryRepository;

        public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository)
        {
            _pieRepository = pieRepository;
            _categoryRepository = categoryRepository;
        }
        
        public ViewResult List(string category)
        {
            IEnumerable<Pie> pies;
            string? currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                pies = _pieRepository.AllPies.OrderBy(p => p.PieId);
                currentCategory = "All pies";
            }

            else
            {
                pies = _pieRepository.AllPies.Where(p => p.Category.CategoryName == category).OrderBy(p => p.PieId);
                currentCategory = _categoryRepository.AllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new PieListViewModel(pies, currentCategory));
        }
        public IActionResult Details(int id)
        {
            var pie = _pieRepository.GetPieById(id);

            if (pie == null)
            {
                return NotFound();
            }

            return View(pie);
        }
        public IActionResult Search()
        {
            return View();
        }

        public ViewResult ManagePies()
        {
            IEnumerable<Pie> pies;
            pies = _pieRepository.AllPies.OrderBy(p => p.PieId);

            return View(new ManagePiesViewModel(pies));
        }

        public ViewResult AddPie()
        {
            List<Category> categories;
            categories = _categoryRepository.AllCategories.ToList();
            AddEditPieViewModel vm = new AddEditPieViewModel();
            vm.Categories = categories;

            return View(vm);
        }

        [HttpPost]
        public IActionResult AddPie(AddEditPieViewModel pie)
        {
            Pie p = new Pie()
            {
                PieId = pie.PieId,
                Name = pie.Name,
                ShortDescription = pie.ShortDescription,
                LongDescription = pie.LongDescription,
                AllergyInformation = pie.AllergyInformation,
                Price = pie.Price,
                ImageUrl = pie.ImageUrl,
                ImageThumbnailUrl = pie.ImageThumbnailUrl,
                IsPieOfTheWeek = pie.IsPieOfTheWeek,
                InStock = pie.InStock,
                CategoryId = pie.CategoryId,
                Category = pie.Category
            };

            _pieRepository.CreatePie(p);

            return RedirectToAction("List");
        }

        public IActionResult EditPie(int pieId)
        {
            var selectedPie = _pieRepository.GetPieById(pieId);

            if (selectedPie == null)
            {
                return NotFound();
            }

            List<Category> categories;
            categories = _categoryRepository.AllCategories.ToList();
           
            AddEditPieViewModel vm = new AddEditPieViewModel
            {
                PieId = pieId,
                Name = selectedPie.Name,
                ShortDescription = selectedPie.ShortDescription,
                LongDescription = selectedPie.LongDescription,
                AllergyInformation = selectedPie.AllergyInformation,
                Price = selectedPie.Price,
                ImageUrl = selectedPie.ImageUrl,
                ImageThumbnailUrl = selectedPie.ImageThumbnailUrl,
                IsPieOfTheWeek = selectedPie.IsPieOfTheWeek,
                InStock = selectedPie.InStock,
                CategoryId = selectedPie.CategoryId,
                Category = selectedPie.Category,
                Categories = categories
            };

            return View(vm);     
        }

        [HttpPost]
        public IActionResult EditPie(AddEditPieViewModel pie)
        {
            Pie p = new Pie()
            {
                PieId = pie.PieId,
                Name = pie.Name,
                ShortDescription = pie.ShortDescription,
                LongDescription = pie.LongDescription,
                AllergyInformation = pie.AllergyInformation,
                Price = pie.Price,
                ImageUrl = pie.ImageUrl,
                ImageThumbnailUrl = pie.ImageThumbnailUrl,
                IsPieOfTheWeek = pie.IsPieOfTheWeek,
                InStock = pie.InStock,
                CategoryId = pie.CategoryId,
                Category = pie.Category
            };

            _pieRepository.UpdatePie(p);

            return RedirectToAction("List");
        }
         
        public IActionResult DeletePie(int pieId)
        {
            var selectedPie = _pieRepository.GetPieById(pieId);

            if (selectedPie == null) return NotFound();

            return View();
        }

        [HttpPost]
        public IActionResult DeletePie(Pie pie)
        {
            var selectedPie = _pieRepository.GetPieById(pie.PieId);

            if (selectedPie != null)
            {
                _pieRepository.RemovePie(selectedPie);
            }

            return RedirectToAction("List");
        }
    }
}

KRISTINA VEZBA/Pages/CheckoutComplete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KRISTINA_VEZBA.Pages
{
    public class CheckoutCompleteModel : PageModel
    {
        public void OnGet()
        {
            ViewData["CheckoutCompleteMessage"] = "Thanks for your order. You'll soon enjoy our delicious pies!";
        }
    }
}

KRISTINA VEZBA/Pages/OrderHistory.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using KRISTINA_VEZBA.Models;

namespace KRISTINA_VEZBA.Pages
{
    public class OrderHistoryModel : PageModel
    {
        private readonly IOrderRepository _orderRepository;

        public OrderHistoryModel(IOrderRepository orderRepository)
        {
           _orderRepository = orderRepository;
        }

        public string UserId { get; set; }
        public Order Order { get; set; }

        public void OnGet()
        {
        }

        public IActionResult OnPost(string Username)
        {
            _orderRepository.GetAllOrders(Username);
            return Page();
        }
    }
}

KRISTINA VEZBA/Views/Order/Checkout.cshtml
@model Order

<form asp-action="Checkout" method="post" role="form">
    <h3 class="my-5">
        You're just one step away from your delicious pies.
    </h3>

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="col-6">
        <div class="row g-2">
            <div class="col-12">
                <label asp-for="FirstName" class="form-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="col-12">
                <label asp-for="LastName" class="form-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>

            <div class="col-12">
                <label asp-for="AddressLine1" class="form-label"></label>
                <input asp-for="AddressLine1" class="form-control" />
                <span asp-validation-for="AddressLine1" class="text-danger"></span>
            </div>

            <div class="col-12">
                <label asp-for="AddressLine2" class="form-label"></label>
                <input asp-for="AddressLine2" class="form-control" />
                <span asp-validation-for="AddressLine2" class="text-danger"></span>
            </div>

            <div class="col-6">
                <label asp-for="City" class="form-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>

            <div class="col-6">
                <label asp-for="State" class="form-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>

            <div class="col-6">
                <label asp-for="ZipCode" class="form-label"></label>
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>

            <div class="col-6">
                <label asp-for="Country" class="form-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>

            <div class="col-12">
                <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="col-12">
                <label asp-for="PhoneNumber" class="form-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="mt-2">
            <div class="col-md-offset-2 col-md-5">
                <input type="submit" class="btn btn-secondary" value="Complete order" />
            </div>
        </div>
    </div>
</form>

KRISTINA VEZBA/Views/Order/CheckoutComplete.cshtml
<h3 class="my-5">
    @ViewBag.CheckoutCompleteMessage
</h3>

KRISTINA VEZBA/Views/Order/OrderHistory.cshtml
@model List<KRISTINA_VEZBA.Models.Order>

@{
    ViewData["Title"] = "OrderHistory";
}

<h1>OrderHistory</h1>
<br />
<div class="row gx-3">
    @foreach (var order in Model)
    {
        <h4>Orders</h4>
        <form asp-action="OrderHistory">
            <input type="hidden" asp-for="@order.Email" />
        </form>
        <hr />
    <div class="col-8">
        @foreach(var detail in order.OrderDetails)
        {
            <div class="card shopping-cart-card mb-2">
                <div class="row">
                    <div class="col-md-4">
                        <img src="@detail.Pie.ImageThumbnailUrl" class="img-fluid rounded-start p-2" alt="@detail.Pie.Name">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-text">@detail.Amount x @detail.Pie.Name</h5>
                            <div class="d-flex justify-content-between">
                                <h6>@detail.Pie.ShortDescription</h6>
                                <h2>@detail.Pie.Price.ToString("c")</h2> <br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="col-4">
        <div class="card shopping-cart-card p-3">
            <div class="row">
                <h4 class="col">Total:</h4>
                <h4 class="col text-end">@order.OrderTotal.ToString("c")</h4>
            </div>
        </div>
        <div class="card shopping-cart-card p-3">
            <div class="row">
                <h4 class="col">Order placed:</h4>
                <h4 class="col text-end">@order.OrderPlaced</h4>
            </div>
        </div>
    </div>
    }
</div>
<div>
    <a asp-controller="Pie" asp-action="List">Back to List</a>
</div>